from __future__ import annotations

from collections.abc import Iterable

from tg_vacancy_bot.models import Vacancy


POSITIVE_IT_TERMS = [
    "developer",
    "engineer",
    "software",
    "backend",
    "frontend",
    "full stack",
    "devops",
    "data scientist",
    "machine learning",
    "python",
    "javascript",
    "typescript",
    "react",
    "разработчик",
    "инженер",
    "программист",
]

NEGATIVE_TERMS = [
    "embedded",
    "firmware",
    "iot",
    "robotics",
    "course",
    "bootcamp",
    "cleaner",
    "janitor",
    "office manager",
    "sales",
    "marketing",
    "support",
    "driver",
    "courier",
    "recruiter",
    "hr manager",
    "account manager",
    "customer success",
    "devops",
    "sre",
    "site reliability engineer",
    "cloud engineer",
    "platform engineer",
    "infrastructure engineer",
    "database administrator",
    "dba",
    "sql administrator",
    "network engineer",
    "sysadmin",
    "system administrator",
    "linux administrator",
    "unix administrator",
    "manual qa",
    "manual tester",
    "sdet",
    "software development engineer in test",
    "appsec",
    "application security",
    "security engineer",
    "security analyst",
    "solution architect",
    "engineering manager",
    "technical pm",
    "technical product manager",
    "technical project manager",
    "product manager",
    "project manager",
    "business analyst",
    "product owner",
    "scrum master",
    "product designer",
    "graphic designer",
    "web designer",
    "technical writer",
    "implementation engineer",
    "solutions consultant",
    "solution consultant",
    "technical support",
    "курс",
    "обучение",
    "уборщик",
    "уборщица",
    "офис-менеджер",
    "офис менеджер",
    "продажи",
    "маркетинг",
    "поддержка",
    "водитель",
    "курьер",
    "рекрутер",
    "devops",
    "sre",
    "системный администратор",
    "сисадмин",
    "сетевой инженер",
    "ручное тестирование",
    "ручной тестировщик",
    "технический писатель",
    "техническая поддержка",
    "бизнес аналитик",
    "продуктовый менеджер",
    "проектный менеджер",
    "менеджер продукта",
    "менеджер проекта",
]


DEVELOPMENT_ROLE_TERMS = [
    "backend",
    "back-end",
    "back end",
    "frontend",
    "front-end",
    "front end",
    "fullstack",
    "full-stack",
    "full stack",
    "ios developer",
    "ios engineer",
    "android developer",
    "android engineer",
    "flutter developer",
    "flutter engineer",
    "react native developer",
    "react native engineer",
    "mobile developer",
    "mobile engineer",
    "game developer",
    "gameplay developer",
    "game backend developer",
    "unity developer",
    "unreal developer",
    "ui/ux",
    "ux/ui",
    "ui designer",
    "ux designer",
    "llm",
    "ai engineer",
    "ai developer",
    "ai/ml engineer",
    "ml engineer",
    "machine learning engineer",
    "machine learning developer",
    "devsecops",
    "automation qa",
    "qa automation",
    "test automation engineer",
    "software architect",
    "technical lead",
    "artificial intelligence engineer",
    "artificial intelligence developer",
    "developer",
    "software engineer",
    "python engineer",
    "python developer",
    "java engineer",
    "java developer",
    "go engineer",
    "go developer",
    "golang engineer",
    "golang developer",
    "node.js engineer",
    "node.js developer",
    "react engineer",
    "react developer",
    "vue engineer",
    "vue developer",
    "angular engineer",
    "angular developer",
    "typescript engineer",
    "typescript developer",
    "javascript engineer",
    "javascript developer",
    "разработчик",
    "программист",
    "backend-разработчик",
    "frontend-разработчик",
    "фронтенд",
    "бэкенд",
    "машинное обучение",
    "ml-инженер",
    "ai-инженер",
]


def filter_it_vacancies(vacancies: Iterable[Vacancy]) -> list[Vacancy]:
    return [
        vacancy
        for vacancy in vacancies
        if looks_like_development_vacancy(" ".join([vacancy.title, vacancy.description]))
    ]


def looks_like_it_vacancy(text: str) -> bool:
    lower = text.lower()
    return any(token in lower for token in POSITIVE_IT_TERMS) and not any(token in lower for token in NEGATIVE_TERMS)


def looks_like_development_vacancy(text: str) -> bool:
    lower = text.lower()
    return any(token in lower for token in DEVELOPMENT_ROLE_TERMS) and not any(
        token in lower for token in NEGATIVE_TERMS
    )
